#include "./parser/config.c"
#include "./parser/help.c"
#include "./parser/constants.c"
#include "./parser/variables.c"
#include "./parser/inbuilt.c"
#include "./parser/parser.c"
#include "./parser/linwrap.c"
#include "./parser/polywrap.c"